// <auto-generated />
using System;
using BookIssues.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BookIssues.API.Migrations
{
    [DbContext(typeof(BookIssuesAPIContext))]
    [Migration("20210116120422_initial-create")]
    partial class initialcreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("BookIssues.API.Models.BookIssues", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("book_id")
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("due_date")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("issue_date")
                        .HasColumnType("datetime2");

                    b.Property<string>("issue_status")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("member_email")
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("id");

                    b.ToTable("BookIssues");

                    b.HasData(
                        new
                        {
                            id = "1",
                            book_id = "978-0062316097",
                            due_date = new DateTime(2016, 1, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            issue_date = new DateTime(2021, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            issue_status = "Returned",
                            member_email = "admin@email.com"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
